-
  name: 'DemoServer welcome'
  uriPattern: ''
  defaults:
    '@package':    'Acme.DemoServer'
    '@controller': 'Standard'

-
  name: 'DemoServer login'
  uriPattern: 'login(/@action)'
  defaults:
    '@package':    'Acme.DemoServer'
    '@controller': 'Login'
    '@action':     'index'
