-
  name: 'DemoServer welcome'
  uriPattern: ''
  defaults:
    '@package':    'Flowpack.SingleSignOn.DemoServer'
    '@controller': 'Standard'
    '@action':     'index'

-
  name: 'DemoServer login'
  uriPattern: 'login(/{@action})'
  defaults:
    '@package':    'Flowpack.SingleSignOn.DemoServer'
    '@controller': 'Login'
    '@action':     'index'

-
  name: 'DemoServer sessions'
  uriPattern: 'sessions(/{@action})'
  defaults:
    '@package':    'Flowpack.SingleSignOn.DemoServer'
    '@controller': 'Sessions'
    '@action':     'index'
  appendExceedingArguments: TRUE

-
  name: 'DemoServer test user service with action'
  uriPattern: 'test/user/{@action}'
  defaults:
    '@package':    'Flowpack.SingleSignOn.DemoServer'
    '@controller': 'Test\User'

-
  name: 'DemoServer test session service with action'
  uriPattern: 'test/session/{@action}'
  defaults:
    '@package':    'Flowpack.SingleSignOn.DemoServer'
    '@controller': 'Test\Session'
