TYPO3:
  Flow:
    security:
      authentication:
        providers:
          DefaultProvider:
            provider: PersistedUsernamePasswordProvider
            requestPatterns:
              controllerObjectName: 'Acme\DemoServer\Controller\.*'
            entryPoint: WebRedirect
            entryPointOptions:
              uri: 'sso/login'
